# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master
pool: 'self-owned'
name: "INSTZHANGK2019"

steps:

- script: echo Hello!
  displayName: 'Run a one-line script'

- task: CmdLine@2
  inputs:
    script: 'powershell.exe -file "c:\autoinstall\InstallandTest.ps1"'

- task: CmdLine@2
  inputs:
    script: '"C:\q.cmd"'

- task: CmdLine@2
  inputs:
    script: 'C:\autoinstall\CheckHTMLHELP.bat'